// <auto-generated />
using System;
using LTWeb_TBDT.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LTWeb_TBDT.Migrations
{
    [DbContext(typeof(BanThietBiDienTuContext))]
    [Migration("20241211154358_UpdateDatabase")]
    partial class UpdateDatabase
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.35")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("LTWeb_TBDT.Data.Admin", b =>
                {
                    b.Property<int>("MaAdmin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaAdmin"), 1L, 1);

                    b.Property<int?>("MaTaiKhoan")
                        .HasColumnType("int");

                    b.HasKey("MaAdmin")
                        .HasName("PK__Admin__49341E38FF5B4347");

                    b.HasIndex("MaTaiKhoan");

                    b.ToTable("Admin", (string)null);
                });

            modelBuilder.Entity("LTWeb_TBDT.Data.ChiTietHoaDon", b =>
                {
                    b.Property<int>("MaHoaDon")
                        .HasColumnType("int");

                    b.Property<int>("MaSanPham")
                        .HasColumnType("int");

                    b.Property<decimal>("GiaBan")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.Property<decimal?>("ThanhTien")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("decimal(29,2)")
                        .HasComputedColumnSql("([SoLuong]*[GiaBan])", false);

                    b.HasKey("MaHoaDon", "MaSanPham")
                        .HasName("PK__ChiTietH__4CF2A579D2DA5004");

                    b.HasIndex("MaSanPham");

                    b.ToTable("ChiTietHoaDon", (string)null);
                });

            modelBuilder.Entity("LTWeb_TBDT.Data.DanhMuc", b =>
                {
                    b.Property<int>("MaDanhMuc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDanhMuc"), 1L, 1);

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenDanhMuc")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("MaDanhMuc")
                        .HasName("PK__DanhMuc__B375088716F192A7");

                    b.ToTable("DanhMuc", (string)null);
                });

            modelBuilder.Entity("LTWeb_TBDT.Data.HoaDon", b =>
                {
                    b.Property<int>("MaHoaDon")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaHoaDon"), 1L, 1);

                    b.Property<int?>("MaKhachHang")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayDatHang")
                        .HasColumnType("date");

                    b.Property<decimal?>("TongTien")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TrangThai")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaHoaDon")
                        .HasName("PK_HOADON");

                    b.HasIndex("MaKhachHang");

                    b.ToTable("HoaDon", (string)null);
                });

            modelBuilder.Entity("LTWeb_TBDT.Data.KhachHang", b =>
                {
                    b.Property<int>("MaKhachHang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaKhachHang"), 1L, 1);

                    b.Property<string>("DiaChi")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("MaTaiKhoan")
                        .HasColumnType("int");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("TenKhachHang")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaKhachHang")
                        .HasName("PK__KhachHan__88D2F0E5CEFECF00");

                    b.HasIndex("MaTaiKhoan");

                    b.ToTable("KhachHang", (string)null);
                });

            modelBuilder.Entity("LTWeb_TBDT.Data.NhanVien", b =>
                {
                    b.Property<int>("MaNhanVien")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaNhanVien"), 1L, 1);

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("MaTaiKhoan")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgaySinh")
                        .HasColumnType("date");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("TenNhanVien")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaNhanVien")
                        .HasName("PK__NhanVien__77B2CA473B0847BE");

                    b.HasIndex("MaTaiKhoan");

                    b.ToTable("NhanVien", (string)null);
                });

            modelBuilder.Entity("LTWeb_TBDT.Data.NhaSanXuat", b =>
                {
                    b.Property<int>("MaNhaSanXuat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaNhaSanXuat"), 1L, 1);

                    b.Property<string>("DiaChi")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("TenNhaSanXuat")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("MaNhaSanXuat")
                        .HasName("PK__NhaSanXu__838C17A1CB300A4E");

                    b.ToTable("NhaSanXuat", (string)null);
                });

            modelBuilder.Entity("LTWeb_TBDT.Data.SanPham", b =>
                {
                    b.Property<int>("MaSanPham")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaSanPham"), 1L, 1);

                    b.Property<decimal>("GiaBan")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("HinhAnh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MaDanhMuc")
                        .HasColumnType("int");

                    b.Property<int?>("MaNhaSanXuat")
                        .HasColumnType("int");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SoLuongTon")
                        .HasColumnType("int");

                    b.Property<string>("TenSanPham")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("MaSanPham")
                        .HasName("PK__SanPham__FAC7442DC4C305D0");

                    b.HasIndex("MaDanhMuc");

                    b.HasIndex("MaNhaSanXuat");

                    b.ToTable("SanPham", (string)null);
                });

            modelBuilder.Entity("LTWeb_TBDT.Data.TaiKhoan", b =>
                {
                    b.Property<int>("MaTaiKhoan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaTaiKhoan"), 1L, 1);

                    b.Property<string>("LoaiTaiKhoan")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TenDangNhap")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaTaiKhoan")
                        .HasName("PK__TaiKhoan__AD7C65296AF814DA");

                    b.ToTable("TaiKhoan", (string)null);
                });

            modelBuilder.Entity("LTWeb_TBDT.Data.TonKho", b =>
                {
                    b.Property<int>("MaSanPham")
                        .HasColumnType("int");

                    b.Property<int?>("SoLuongTon")
                        .HasColumnType("int");

                    b.HasKey("MaSanPham")
                        .HasName("PK__TonKho__FAC7442D17CBA4B5");

                    b.ToTable("TonKho", (string)null);
                });

            modelBuilder.Entity("LTWeb_TBDT.Data.Admin", b =>
                {
                    b.HasOne("LTWeb_TBDT.Data.TaiKhoan", "MaTaiKhoanNavigation")
                        .WithMany("Admins")
                        .HasForeignKey("MaTaiKhoan")
                        .HasConstraintName("FK__Admin__MaTaiKhoa__3C69FB99");

                    b.Navigation("MaTaiKhoanNavigation");
                });

            modelBuilder.Entity("LTWeb_TBDT.Data.ChiTietHoaDon", b =>
                {
                    b.HasOne("LTWeb_TBDT.Data.HoaDon", "MaHoaDonNavigation")
                        .WithMany("ChiTietHoaDons")
                        .HasForeignKey("MaHoaDon")
                        .IsRequired()
                        .HasConstraintName("FK__ChiTietHo__MaHoa__4CA06362");

                    b.HasOne("LTWeb_TBDT.Data.SanPham", "MaSanPhamNavigation")
                        .WithMany("ChiTietHoaDons")
                        .HasForeignKey("MaSanPham")
                        .IsRequired()
                        .HasConstraintName("FK__ChiTietHo__MaSan__4D94879B");

                    b.Navigation("MaHoaDonNavigation");

                    b.Navigation("MaSanPhamNavigation");
                });

            modelBuilder.Entity("LTWeb_TBDT.Data.HoaDon", b =>
                {
                    b.HasOne("LTWeb_TBDT.Data.KhachHang", "MaKhachHangNavigation")
                        .WithMany("HoaDons")
                        .HasForeignKey("MaKhachHang")
                        .HasConstraintName("FK__HoaDon__MaKhachH__49C3F6B7");

                    b.Navigation("MaKhachHangNavigation");
                });

            modelBuilder.Entity("LTWeb_TBDT.Data.KhachHang", b =>
                {
                    b.HasOne("LTWeb_TBDT.Data.TaiKhoan", "MaTaiKhoanNavigation")
                        .WithMany("KhachHangs")
                        .HasForeignKey("MaTaiKhoan")
                        .HasConstraintName("FK__KhachHang__MaTai__3F466844");

                    b.Navigation("MaTaiKhoanNavigation");
                });

            modelBuilder.Entity("LTWeb_TBDT.Data.NhanVien", b =>
                {
                    b.HasOne("LTWeb_TBDT.Data.TaiKhoan", "MaTaiKhoanNavigation")
                        .WithMany("NhanViens")
                        .HasForeignKey("MaTaiKhoan")
                        .HasConstraintName("FK__NhanVien__MaTaiK__398D8EEE");

                    b.Navigation("MaTaiKhoanNavigation");
                });

            modelBuilder.Entity("LTWeb_TBDT.Data.SanPham", b =>
                {
                    b.HasOne("LTWeb_TBDT.Data.DanhMuc", "MaDanhMucNavigation")
                        .WithMany("SanPhams")
                        .HasForeignKey("MaDanhMuc")
                        .HasConstraintName("FK__SanPham__MaDanhM__46E78A0C");

                    b.HasOne("LTWeb_TBDT.Data.NhaSanXuat", "MaNhaSanXuatNavigation")
                        .WithMany("SanPhams")
                        .HasForeignKey("MaNhaSanXuat")
                        .HasConstraintName("FK__SanPham__MaNhaSa__45F365D3");

                    b.Navigation("MaDanhMucNavigation");

                    b.Navigation("MaNhaSanXuatNavigation");
                });

            modelBuilder.Entity("LTWeb_TBDT.Data.TonKho", b =>
                {
                    b.HasOne("LTWeb_TBDT.Data.SanPham", "MaSanPhamNavigation")
                        .WithOne("TonKho")
                        .HasForeignKey("LTWeb_TBDT.Data.TonKho", "MaSanPham")
                        .IsRequired()
                        .HasConstraintName("FK__TonKho__MaSanPha__5070F446");

                    b.Navigation("MaSanPhamNavigation");
                });

            modelBuilder.Entity("LTWeb_TBDT.Data.DanhMuc", b =>
                {
                    b.Navigation("SanPhams");
                });

            modelBuilder.Entity("LTWeb_TBDT.Data.HoaDon", b =>
                {
                    b.Navigation("ChiTietHoaDons");
                });

            modelBuilder.Entity("LTWeb_TBDT.Data.KhachHang", b =>
                {
                    b.Navigation("HoaDons");
                });

            modelBuilder.Entity("LTWeb_TBDT.Data.NhaSanXuat", b =>
                {
                    b.Navigation("SanPhams");
                });

            modelBuilder.Entity("LTWeb_TBDT.Data.SanPham", b =>
                {
                    b.Navigation("ChiTietHoaDons");

                    b.Navigation("TonKho");
                });

            modelBuilder.Entity("LTWeb_TBDT.Data.TaiKhoan", b =>
                {
                    b.Navigation("Admins");

                    b.Navigation("KhachHangs");

                    b.Navigation("NhanViens");
                });
#pragma warning restore 612, 618
        }
    }
}
